config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "vanillas/omikuji"
  get "vanillas/pwd_generator"

  get "home/top"


  root "home#top"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/vanillas_controller.rb
class VanillasController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/top.html.haml
.home-wrapper
  .homeMenu
    .homeMenu-title
      リスト
    .homeMenu-list
      = link_to "・おみくじ", vanillas_omikuji_path, class: "homeMenu-listItem"
    .homeMenu-list
      = link_to "・パスワードジェネレータ", vanillas_pwd_generator_path, class: "homeMenu-listItem"
    .homeMenu-list
      = link_to "・みっつめ", "#", class: "homeMenu-listItem"
    .homeMenu-list
      = link_to "・よっつめ", "#", class: "homeMenu-listItem"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RoomJS
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/vanillas/omikuji.html.haml
.omikuji
  .omikuji-title
    おみくじ
  .omikuji-wrapper
    #omikuji-btn
      引く

app/views/vanillas/pwd_generator.haml
.pwdGen
  .pwdGen-title
    〜パスワードジェネレータ〜
  .pwdGen-wrapper
    .pwdContainer
      %p
        %input{type: "text", id: "btnResult" }
      %p
        #pwdBtn
          Generate Password
      %fieldset
        %legend
          Options
        %p
          Length:(
          %span#pwdLabel
            8
          )
          %input{type: "range", id: "pwdSlider", value: "8", min: "4", max: "20"}
        %p
          Numbers?:
          %input{type: "checkbox", id: "pwdNumbers"}
          Symbols?
          %input{type: "checkbox", id: "pwdSymbols"}